### ISSUE TITLE
`model_json_schema` error when using a Union dtype

### ISSUE THREAD

**Issue by tanguyMichardiere** [p2p-ld/numpydantic#38]
Hello,

Minimal reproduction:

```python
import numpy as np
from numpydantic import NDArray, Shape
from pydantic import BaseModel


class Model(BaseModel):
    root: NDArray[Shape["*, ..."], np.int64 | np.str_]


Model.model_json_schema()
```

```
Traceback (most recent call last):
[...]
File "[...]/numpydantic/ndarray.py", line 211, in __get_pydantic_json_schema__
    json_schema["dtype"] = ".".join([dtype.__module__, dtype.__name__])
                                                       ^^^^^^^^^^^^^^
AttributeError: 'types.UnionType' object has no attribute '__name__'. Did you mean: '__ne__'?
```

I also tried using a tuple of dtypes instead of a Union, which allows generating the JSON schema. Unfortunately, it doesn't work with `np.str_`:

```python
import numpy as np
from numpydantic import NDArray, Shape
from pydantic import BaseModel


class Model(BaseModel):
    root: NDArray[Shape["*, ..."], (np.int64, np.str_)]


Model(root=np.array(["a", "bc"]))
```

```
Traceback (most recent call last):
[...]
  File "[...]/pydantic/main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for StateArray
root
  Value error, Invalid dtype! expected (<class 'numpy.int64'>, <class 'numpy.str_'>), got <U2 [type=value_error, input_value=array(['a', 'bc'], dtype='<U2'), input_type=ndarray]
    For further information visit https://errors.pydantic.dev/2.10/v/value_error
```

I am using Python 3.13.1, Numpy 2.2.0, Pydantic 2.10.3 and Numpydantic 1.6.5

**Comment by sneakers-the-rat** [comment]
ope, will fix in the morning. we must not have unions in the dtype test cases yet. will add and then correct that - `typing` types are always difficult to handle since they often lack basic python object properties like this!

**Comment by sneakers-the-rat** [comment]
oh omg this is yet another nptyping bug.

apparently `hash(typeA | typeB) == hash(Union[typeA, typeB])` despite one being a `types.UnionType` and the other being a `typing.Union`..... so since nptyping caches types instead of creating new ones (for some reason???) it masks the error in the tests

**Comment by sneakers-the-rat** [comment]
First part of bug resolved - https://github.com/p2p-ld/numpydantic/pull/39
Now fixing using `np.str_` (normally that would just be `str`, but we should support `np.str_`)

**Comment by sneakers-the-rat** [comment]
OK should be good now in 1.6.6 - https://numpydantic.readthedocs.io/en/latest/changelog.html#id3

Confirmed that these both work now

```python
import numpy as np
from numpydantic import NDArray, Shape
from pydantic import BaseModel
import json


class Model(BaseModel):
    root: NDArray[Shape["*, ..."], np.int64 | np.str_]


json.dumps(Model.model_json_schema(), indent=2)
```

```json
{
  "$defs": {
    "any-shape-array-1af4072942bc3210": {
      "anyOf": [
        {
          "items": {
            "$ref": "#/$defs/any-shape-array-1af4072942bc3210"
          },
          "type": "array"
        },
        {
          "maximum": 9223372036854775807,
          "minimum": -9223372036854775808,
          "type": "integer"
        },
        {
          "type": "string"
        }
      ]
    }
  },
  "properties": {
    "root": {
      "items": {
        "$ref": "#/$defs/any-shape-array-1af4072942bc3210"
      },
      "title": "Root",
      "type": "array"
    }
  },
  "required": [
    "root"
  ],
  "title": "Model",
  "type": "object"
}
```

```python
import numpy as np
from numpydantic import NDArray, Shape
from pydantic import BaseModel


class Model(BaseModel):
    root: NDArray[Shape["*, ..."], (np.int64, np.str_)]
```

```python
>>> Model(root=np.array(["a", "bc"]))
Model(root=array(['a', 'bc'], dtype='<U2'))
```
